server:
  port: 9092

spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: false
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:mysql://localhost:3306/bank?createDatabaseIfNotExist=true
    username: root
    password: bank
